/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Hajiebrahimi
 */

#include <bits/stdc++.h>


using namespace std;


typedef long long ll;
typedef long double ld;
typedef pair<ll, ll> pll;
typedef pair<double, double> pdd;
typedef pair<ld, ld> pld;
typedef pair<string, string> pss;

#define all(x)                      (x).begin(),(x).end()
#define Sort(x)                     sort(all((x)))
#define X                           first
#define Y                           second
#define sep                         ' '
#define endl                        '\n'
#define fast_io                     ios::sync_with_stdio(false);cin.tie(0);cout.tie(0);
#define set_random                  mt19937_64 rng(chrono::steady_clock::now().time_since_epoch().count());


const ll MAXN = 1e6 + 10;
const ll INF = 8e18;
const ll MOD = 1e9 + 7;
ll n;
string s,t;
map<string,string> par;
vector<string>vec;
string Find(string v)
{
    return (par[v] == v ? v : par[v] = Find(par[v]));
}
int main() {
    fast_io;
    cin>>n;
    for(ll i=0;i<n;i++){
        cin>>s>>t;
        if(par[s]=="")vec.push_back(s);
        par[t]=t;
        par[s]=par[t];
    }
    cout<<vec.size()<<endl;
    for(string s:vec){
        cout<<s<<sep<<Find(s)<<endl;
    }
    return 0;
}
